### ISSUE TITLE
 try implementing different optimization algorithms

### ISSUE THREAD

**Issue by chakpongchung** [cs164fall2018/pa3-chocopy-code-generation#7]
I want to implement different optimization algorithms on the typed AST( https://github.com/cs164berkeley/pa3-chocopy-code-generation/tree/master/src/test/data/pa3 ) and measure it using the instruction count from Venus. Being able to debug by setting breakpoints is needed. Otherwise, it is quite hard to debug. I want to parse the typed AST in json format but I do not find a way to parse it into a `Program` object using jackson or Gson.  Some online tools are available like the following:
https://www.jsonschema2pojo.org/
https://transform.tools/json-to-json-schema

 but hey are not able to parse Optional field in some typed AST json.
 
 Reading the json AST into `Map<?, ?>` could be a way, but it would be very inconvenient when accessing the child nodes:
 
 ```
         ObjectMapper objectMapper = new ObjectMapper();
        // convert JSON file to map
        Map<?, ?> map = objectMapper.readValue(Paths.get(path).toFile(), Map.class);
        System.out.println(map.containsKey("location"));
        System.out.println(map.containsKey("locationXYZ"));
 ```

https://github.com/cs164berkeley/pa3-chocopy-code-generation/blob/master/src/main/java/chocopy/pa3/StudentCodeGen.java#L15

It seems like the `process()` function is used by the chocopy-ref.jar when doing the testing. Can I run it without using the `chocopy-ref.jar` ? I can create my own public static void main(String[] args) in this file but still need to parse the typed AST json. Ideally, I dont need to feed the Program object from PA2/PA1 so to decouple this effort from them. Doing so future students can learn advanced optimization techniques like  phase 4 and 5 here:
https://github.com/6035/sp21

@rohanpadhye @ksen007

**Comment by rohanpadhye** [comment]
The project already contains sufficient scaffolding for serializing/de-serializing the AST into/from JSON. See, for example: https://github.com/cs164berkeley/pa3-chocopy-code-generation/blob/6e393b9acf337caccbf927156957f520ed7d5821/src/main/java/chocopy/common/astnodes/Node.java#L154-L156

And it's opposite:
https://github.com/cs164berkeley/pa3-chocopy-code-generation/blob/6e393b9acf337caccbf927156957f520ed7d5821/src/main/java/chocopy/common/astnodes/Node.java#L134-L135

For any JSON produced by the ChocoPy reference compiler, the result of `Node.fromJSON()` is always a node of type `Program`.

Hope this helps.

**Comment by chakpongchung** [comment]
@rohanpadhye 
Very excited to see this part! Let me know if I can move this to somewhere to benefit more people! Maybe as a question with tag `chocopy` on stackoverflow before closing it?
